export interface SeedCategory {
  name: string;
  items: { name: string; unit: string }[];
}

export const DEFAULT_CATALOG: SeedCategory[] = [
  {
    name: "Féculents & céréales",
    items: [
      { name: "Spaghetti", unit: "g" },
      { name: "Penne", unit: "g" },
      { name: "Riz", unit: "g" },
      { name: "Pommes de terre", unit: "g" },
      { name: "Semoule / Couscous", unit: "g" },
      { name: "Quinoa", unit: "g" },
      { name: "Lentilles", unit: "g" },
      { name: "Pois chiches", unit: "g" },
      { name: "Farine", unit: "g" },
    ],
  },
  {
    name: "Légumes",
    items: [
      { name: "Tomates", unit: "pièce" },
      { name: "Oignons", unit: "pièce" },
      { name: "Ail", unit: "gousse" },
      { name: "Carottes", unit: "pièce" },
      { name: "Courgettes", unit: "pièce" },
      { name: "Poivrons", unit: "pièce" },
      { name: "Aubergine", unit: "pièce" },
      { name: "Champignons", unit: "g" },
      { name: "Épinards", unit: "g" },
      { name: "Haricots verts", unit: "g" },
      { name: "Petits pois", unit: "g" },
      { name: "Maïs", unit: "g" },
      { name: "Brocoli", unit: "pièce" },
      { name: "Salade", unit: "pièce" },
      { name: "Concombre", unit: "pièce" },
      { name: "Céleri", unit: "branche" },
    ],
  },
  {
    name: "Fruits",
    items: [
      { name: "Pommes", unit: "pièce" },
      { name: "Bananes", unit: "pièce" },
      { name: "Citrons", unit: "pièce" },
      { name: "Oranges", unit: "pièce" },
      { name: "Fraises", unit: "g" },
      { name: "Raisins", unit: "g" },
    ],
  },
  {
    name: "Viandes",
    items: [
      { name: "Poulet", unit: "g" },
      { name: "Bœuf haché", unit: "g" },
      { name: "Steak", unit: "pièce" },
      { name: "Porc", unit: "g" },
      { name: "Lardons", unit: "g" },
      { name: "Jambon", unit: "tranche" },
      { name: "Saucisses", unit: "pièce" },
      { name: "Agneau", unit: "g" },
    ],
  },
  {
    name: "Poissons & fruits de mer",
    items: [
      { name: "Saumon", unit: "g" },
      { name: "Cabillaud", unit: "g" },
      { name: "Thon en boîte", unit: "boîte" },
      { name: "Sardines", unit: "boîte" },
      { name: "Crevettes", unit: "g" },
    ],
  },
  {
    name: "Produits laitiers",
    items: [
      { name: "Œufs", unit: "pièce" },
      { name: "Lait", unit: "ml" },
      { name: "Beurre", unit: "g" },
      { name: "Crème fraîche", unit: "ml" },
      { name: "Yaourt", unit: "pièce" },
      { name: "Fromage blanc", unit: "g" },
    ],
  },
  {
    name: "Fromages",
    items: [
      { name: "Cheddar", unit: "g" },
      { name: "Mozzarella", unit: "g" },
      { name: "Parmesan", unit: "g" },
      { name: "Gruyère", unit: "g" },
      { name: "Feta", unit: "g" },
      { name: "Fromage râpé", unit: "g" },
    ],
  },
  {
    name: "Boulangerie",
    items: [
      { name: "Baguette", unit: "pièce" },
      { name: "Pain de mie", unit: "tranche" },
      { name: "Biscottes", unit: "tranche" },
    ],
  },
  {
    name: "Épicerie & condiments",
    items: [
      { name: "Huile d'olive", unit: "ml" },
      { name: "Huile de tournesol", unit: "ml" },
      { name: "Vinaigre", unit: "ml" },
      { name: "Sel", unit: "g" },
      { name: "Poivre", unit: "g" },
      { name: "Sucre", unit: "g" },
      { name: "Sauce tomate", unit: "ml" },
      { name: "Concentré de tomate", unit: "g" },
      { name: "Mayonnaise", unit: "ml" },
      { name: "Moutarde", unit: "g" },
      { name: "Ketchup", unit: "ml" },
      { name: "Sauce soja", unit: "ml" },
      { name: "Bouillon cube", unit: "pièce" },
      { name: "Miel", unit: "g" },
      { name: "Olives", unit: "g" },
    ],
  },
  {
    name: "Herbes & épices",
    items: [
      { name: "Basilic", unit: "pincée" },
      { name: "Persil", unit: "pincée" },
      { name: "Thym", unit: "pincée" },
      { name: "Origan", unit: "pincée" },
      { name: "Romarin", unit: "pincée" },
      { name: "Laurier", unit: "feuille" },
      { name: "Cumin", unit: "pincée" },
      { name: "Paprika", unit: "pincée" },
      { name: "Curry", unit: "pincée" },
      { name: "Curcuma", unit: "pincée" },
      { name: "Cannelle", unit: "pincée" },
    ],
  },
  {
    name: "Boissons",
    items: [
      { name: "Eau", unit: "L" },
      { name: "Jus d'orange", unit: "L" },
      { name: "Café", unit: "g" },
      { name: "Thé", unit: "sachet" },
      { name: "Vin blanc", unit: "ml" },
      { name: "Vin rouge", unit: "ml" },
    ],
  },
];
